/**
 * @file
 *   CSV_READER Application Message IDs
 */
#ifndef DEFAULT_CSV_READER_MSGIDS_H
#define DEFAULT_CSV_READER_MSGIDS_H

#include "cfe_core_api_base_msgids.h"

#define CSV_READER_CMD_MID CSV_READER_CMD_PLATFORM_MIDVAL(CMD)
#define CSV_READER_TLM_MID CSV_READER_TLM_PLATFORM_MIDVAL(HK_TLM)
#define CSV_READER_DATA_TLM_MID CSV_READER_TLM_PLATFORM_MIDVAL(DATA_TLM)

#endif
